export interface Plan {
  id: string
  name: string
  tagline: string
  price: string
  users: string
  interactionz: string
  channelPackPrice: string
  channelPackNote: string
  total: string
  totalNote: string
  cta: string
  description: string
  highlighted?: boolean
}

export const PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'STARTER',
    tagline: 'Mensagens em Massa',
    price: 'R$ 0/mês',
    users: '1 usuário',
    interactionz: '100 Interactionz',
    channelPackPrice: 'R$ 100',
    channelPackNote: 'Até 1.000 SMS ou 182 WhatsApp',
    total: 'R$ 100/mês',
    totalNote: '+ Valor de ativação se habilitar canal WhatsApp',
    cta: 'Contrate agora',
    description: 'Impacte mais clientes com envio de comunicações em massa.',
  },
  {
    id: 'specialist',
    name: 'SPECIALIST',
    tagline: 'IA Generativa',
    price: 'R$ 600/mês',
    users: '10 usuários',
    interactionz: '500 Interactionz',
    channelPackPrice: 'R$ 100',
    channelPackNote: 'Até 1.000 SMS ou 182 WhatsApp',
    total: 'R$ 700/mês',
    totalNote: '+ Valor de ativação',
    cta: 'Contrate agora',
    description:
      'Transforme a experiência de seu cliente da atração a conversão.',
    highlighted: true,
  },
  {
    id: 'expert',
    name: 'EXPERT',
    tagline: 'IA Generativa',
    price: 'R$ 1.800/mês',
    users: '30 usuários',
    interactionz: '2.000 Interactionz',
    channelPackPrice: 'R$ 100',
    channelPackNote: 'Até 1.000 SMS ou 182 WhatsApp',
    total: 'R$ 1.900/mês',
    totalNote: '+ Valor de ativação',
    cta: 'Contrate agora',
    description:
      'Revolucione a experiência do cliente com recursos avançados e inteligência.',
  },
  {
    id: 'professional',
    name: 'PROFESSIONAL',
    tagline: 'IA Generativa',
    price: 'R$ 3.900/mês',
    users: '50 usuários',
    interactionz: '5.000 Interactionz',
    channelPackPrice: 'R$ 100',
    channelPackNote: 'Até 1.000 SMS ou 182 WhatsApp',
    total: 'R$ 4.000/mês',
    totalNote: '+ Valor de ativação',
    cta: 'Contrate agora',
    description:
      'Escale e eleve a experiência do cliente com análises para otimizar equipes.',
  },
  {
    id: 'enterprise',
    name: 'ENTERPRISE',
    tagline: 'IA Generativa',
    price: 'Sob consulta',
    users: 'Usuários sob consulta',
    interactionz: 'Interactionz sob consulta',
    channelPackPrice: 'sob consulta',
    channelPackNote: 'Volume de disparos sob consulta.',
    total: 'Sob consulta',
    totalNote: '',
    cta: 'Contrate agora',
    description:
      'Crie jornadas únicas, personalizadas, integradas e automatizadas.',
  },
]

export interface ComparisonRow {
  category?: string
  name: string
  starter: string
  specialist: string
  expert: string
  professional: string
  enterprise: string
}

export const COMPARISON_ROWS: ComparisonRow[] = [
  {
    category: 'Resumo',
    name: 'Mensalidade',
    starter: 'R$ 0',
    specialist: 'R$ 600',
    expert: 'R$ 1.800',
    professional: 'R$ 3.900',
    enterprise: 'Sob consulta',
  },
  {
    name: 'Usuários',
    starter: '1',
    specialist: '10',
    expert: '30',
    professional: '50',
    enterprise: 'Sob consulta',
  },
  {
    name: 'Usuários Adicionais',
    starter: 'R$ 250',
    specialist: 'R$ 150',
    expert: 'R$ 100',
    professional: 'R$ 100',
    enterprise: 'Sob consulta',
  },
  {
    name: 'Interactionz',
    starter: '100',
    specialist: '500',
    expert: '2.000',
    professional: '5.000',
    enterprise: 'Sob consulta',
  },
  {
    name: 'Interactionz Adicionais',
    starter: 'R$ 2,50',
    specialist: 'R$ 1,32',
    expert: 'R$ 0,99',
    professional: 'R$ 0,86',
    enterprise: 'Sob consulta',
  },
  {
    name: 'Setup',
    starter:
      'R$ 649 no primeiro mês caso necessite habilitar os canais WhatsApp e/ou RCS.',
    specialist: 'R$ 649 no primeiro mês',
    expert: 'R$ 1.999 no primeiro mês',
    professional: 'R$ 3.999 no primeiro mês',
    enterprise: 'Sob consulta',
  },
  {
    category: 'Recursos para envio de mensagens',
    name: 'Envio de mensagem em massa',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Exportação de relatórios',
    starter: 'Exportação de dados de envio para CSV',
    specialist: 'Exportação de dados de envio para CSV',
    expert: 'Exportação de dados de envio para CSV',
    professional: 'Exportação de dados de envio para CSV',
    enterprise: '✓',
  },
  {
    name: 'Salve mensagens para reutilizar',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Reengajamento automático',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Converse com seus leads',
    starter: 'Sandbox WhatsApp, Instagram, Facebook Messenger ou Webchat',
    specialist: '+ WhatsApp Business, E-mail',
    expert: '+ WhatsApp Business, E-mail',
    professional: '+ WhatsApp Business, E-mail',
    enterprise: '+ WhatsApp Business, E-mail',
  },
  {
    name: 'Transbordo conversacional',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Envie no melhor horário',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Transferência de atendimento e motivos de fechamento',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Escrita Inteligente',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Processamento em lote (TPS)',
    starter: 'Até 40 msgs/s',
    specialist: 'Até 40 msgs/s',
    expert: 'Até 40 msgs/s',
    professional: 'Até 40 msgs/s',
    enterprise: '✓',
  },
  {
    category: 'Dashboards',
    name: 'Dashboards de análise',
    starter: 'Taxa de atualização: 24h',
    specialist: 'Taxa de atualização: 24h',
    expert: 'Taxa de atualização: 24h',
    professional: 'Taxa de atualização: 24h',
    enterprise: '✓',
  },
  {
    name: 'Geração de Insights',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Bots ativos',
    starter: '1',
    specialist: '5',
    expert: '10',
    professional: '100',
    enterprise: 'Ilimitado',
  },
  {
    category: 'Suporte ao cliente',
    name: 'Atendimento por Tickets',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Campos adicionais de tickets',
    starter: 'Até 10',
    specialist: 'De 11 a 20',
    expert: 'De 21 a 40',
    professional: 'Ilimitado',
    enterprise: '✓',
  },
  {
    name: 'Agentes Especialistas',
    starter: 'Até 15',
    specialist: 'De 16 a 30',
    expert: 'De 31 a 60',
    professional: 'Ilimitado',
    enterprise: '✓',
  },
  {
    name: 'Atendimento conversacional por Chat',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Relatórios',
    starter: 'Relatórios pré-configurados',
    specialist: 'Relatórios pré-configurados',
    expert: 'Relatórios pré-configurados',
    professional: 'Relatórios pré-configurados',
    enterprise: '✓',
  },
  {
    name: 'Análise do ticket por IA',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Assistente de escrita com IA',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Pergunte para a IAs',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Base de conhecimento com IA',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    category: 'Ligações pelo WhatsApp',
    name: 'Realizar e receber ligações',
    starter: 'Cobrança de minutagem',
    specialist: 'Cobrança de minutagem',
    expert: 'Cobrança de minutagem',
    professional: 'Cobrança de minutagem',
    enterprise: '✓',
  },
  {
    name: 'Gravação das chamadas',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Acesso às gravações via interface',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    category: 'Chatbots',
    name: 'Chatbots de fluxos',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Triagem automatizada',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Templates de bots pré-prontos',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Bot com integração de APIs',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Assistente de criação de bots (IA)',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Resposta inteligente usando IA Generativa',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Resposta inteligente a partir de documentos',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Chatbots de IA Generativa',
    starter: '—',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    category: 'Gestão de contatos',
    name: 'Crie contatos, listas e segmentos',
    starter: 'até 1.000 contatos',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Importação de base via CSV',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Página de informações de contato',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    category: 'Produtividade',
    name: 'Modelos de mensagens pré-criados',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Réguas de comunicação automatizadas',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Gestão do time de vendas',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Turbinar postagens (anúncios)',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    category: 'APIs',
    name: 'Acesso às APIs',
    starter: 'Envio de mensagens',
    specialist: 'Envio de mensagens',
    expert: 'Envio, conversas e gestão',
    professional: 'Envio, conversas e gestão',
    enterprise: 'Envio, conversas e gestão',
  },
  {
    name: 'Limite de requisições',
    starter: 'Até 10/s',
    specialist: 'Até 10/s',
    expert: 'Até 15/s',
    professional: 'Até 20/s',
    enterprise: 'Consulte',
  },
  {
    name: 'Chamadas a APIs externas',
    starter: 'Até 150 mil/mês',
    specialist: 'Até 150 mil/mês',
    expert: 'Até 350 mil/mês',
    professional: 'Até 750 mil/mês',
    enterprise: 'Consulte',
  },
  {
    category: 'Governança',
    name: 'Gestão de contas e perfis',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Retenção de dados',
    starter: '3 meses',
    specialist: '6 meses',
    expert: '6 meses',
    professional: '6 meses',
    enterprise: 'Consulte',
  },
  {
    name: 'Armazenamento',
    starter: '300MB',
    specialist: '1GB',
    expert: '2GB',
    professional: '5GB',
    enterprise: 'Consulte',
  },
  {
    category: 'Automações',
    name: 'Gatilhos configuráveis',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Automações simultâneas',
    starter: 'Até 3',
    specialist: 'Até 10',
    expert: 'Até 50',
    professional: '50+',
    enterprise: '✓',
  },
  {
    category: 'Suporte',
    name: 'Certificado ISO 27001',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Central de Ajuda',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'Suporte via chat para admin',
    starter: '✓',
    specialist: '✓',
    expert: '✓',
    professional: '✓',
    enterprise: '✓',
  },
  {
    name: 'SLA primeira resposta',
    starter: 'Até 2h',
    specialist: 'Até 2h',
    expert: 'Até 2h',
    professional: 'Até 2h',
    enterprise: 'Até 2h',
  },
  {
    name: 'SLA resolução crítica',
    starter: 'Até 12h',
    specialist: 'Até 12h',
    expert: 'Até 4h',
    professional: 'Até 4h',
    enterprise: 'Account manager',
  },
  {
    category: 'Integrações',
    name: 'Conectores terceiros',
    starter: 'WBuy, Olist, Bling, Microvix, Omie e mais',
    specialist: 'WBuy, Olist, Bling, Microvix, Omie e mais',
    expert: 'WBuy, Olist, Bling, Microvix, Omie e mais',
    professional: 'WBuy, Olist, Bling, Microvix, Omie e mais',
    enterprise: '✓',
  },
  {
    name: 'Catálogos de produtos',
    starter: 'Mercado Livre',
    specialist: 'Mercado Livre',
    expert: 'Mercado Livre',
    professional: 'Mercado Livre',
    enterprise: '✓',
  },
  {
    name: 'Links de pagamento',
    starter: 'Mercado Pago, Stone e Paypal',
    specialist: 'Mercado Pago, Stone e Paypal',
    expert: 'Mercado Pago, Stone e Paypal',
    professional: 'Mercado Pago, Stone e Paypal',
    enterprise: '✓',
  },
]
